ProyectoAlkemy/ProyectoAlkemy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reserva/', include("reserva.urls")),
    path('', TemplateView.as_view(template_name='reserva/home.html'), name='landing'),
    path('api/',include('api.urls'))
]

ProyectoAlkemy/api/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('servicios/',views.servicios_listado,name="servicios_listado"),
    path('servicios/<int:id_servicio>', views.servicio_por_id,name="servicio_por_id"),
    path('coordinadores/', views.coordinadores_listado,name="coordinadores_listado"),
    path('clientes/',views.clientes_listado,name="clientes_listado"),
    path('empleados/', views.EmpleadosAPI.as_view(), name="api_empleados_listado"),
    path('empleados/eliminar/<int:id_empleado>', views.EmpleadosAPI.as_view(), name="api_eliminar_empleado"),
    path('empleados/<int:id_empleado>',views.EmpleadosAPI.as_view(),name="api_empleado_id"),
    path('empleados/crear',views.EmpleadosAPI.as_view(),name="api_crear_empleado"),
    path('empleados/modificar/<int:id_empleado>',views.EmpleadosAPI.as_view(),name="api_modificar_empleado"),
    path('reserva/', views.ReservaAPI.as_view(), name="api_reserva_listado")
]

ProyectoAlkemy/reserva/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name= "home"),
    path('empleados/nuevo/',views.registrar_empleado,name="registrar_empleado"),
    path('empleados/activar/<int:id_empleado>',views.activar_empleado, name="activar_empleado"),
    path('empleados/listado/', views.listado_empleados, name="listado_empleados"),
    path('empleados/modificar/<int:id_empleado>', views.modificar_empleado, name='modificar_empleado'),
    path('empleados/desactivar/<int:id_empleado>',views.desactivar_empleado, name="desactivar_empleado"),
    path('clientes/listado/', views.listado_clientes, name="listado_clientes"),
    path('clientes/nuevo/',views.registrar_cliente,name="registrar_cliente"),
    path('clientes/desactivar/<int:id_cliente>',views.desactivar_cliente,name="desactivar_cliente"),
    path('clientes/activar/<int:id_cliente>',views.activar_cliente,name="activar_cliente"),
    path('clientes/modificar/<int:id_cliente>',views.modificar_cliente,name="modificar_cliente"),
    path('coordinadores/modificar/<int:id_coordinador>',views.modificar_coordinador,name="modificar_coordinador"),
    path('coordinadores/activar/<int:id_coordinador>',views.activar_coordinador,name="activar_coordinador"),
    path('coordinadores/desactivar/<int:id_coordinador>',views.desactivar_coordinador,name="desactivar_coordinador"),
    path('coordinadores/listado/', views.listado_coordinadores, name="listado_coordinadores"),
    path('coordinadores/nuevo/',views.registrar_coordinador,name="registrar_coordinador"),
    path('nuevo/', views.registrar_reserva_de_servicio,name="registrar_reserva_de_servicio"),
    path('modificar/<int:id_reserva_servicio>', views.modificar_reserva_de_servicio,name="modificar_reserva_de_servicio"),
    path('eliminar/<int:id_reserva_servicio>', views.eliminar_reserva_de_servicio,name="eliminar_reserva_de_servicio"),
    path('listado/', views.listado_reservas_de_servicios,name="listado_reservas_de_servicios"),
    path('servicios/nuevo/',views.registrar_servicio,name="registrar_servicio"),
    path('servicios/modificar/<int:id_servicio>',views.modificar_servicio,name="modificar_servicio"),
    path('servicios/desactivar/<int:id_servicio>',views.desactivar_servicio,name="desactivar_servicio"),
    path('servicios/activar/<int:id_servicio>',views.activar_servicio,name="activar_servicio"),
    path('servicios/listado/', views.listado_servicios, name="listado_servicios"),
]

ProyectoAlkemy/reserva/models.py
from django.db import models

# Create your models here.

class Empleado(models.Model):
    nombre = models.CharField(verbose_name="Nombre",max_length=50)
    apellido = models.CharField(verbose_name="Apellido",max_length=50)
    numero_legajo = models.IntegerField(verbose_name="Numero de legajo", unique=True)
    activo = models.BooleanField(verbose_name="Activo",default=True)
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Coordinador(models.Model):
    nombre = models.CharField(verbose_name="Nombre",max_length=50)
    apellido = models.CharField(verbose_name="Apellido",max_length=50)
    numero_documento = models.IntegerField(verbose_name="Numero de documento", unique=True)
    fecha_alta = models.DateTimeField(verbose_name="Fecha de alta",auto_now_add=True)
    activo = models.BooleanField(verbose_name="Activo",default=True)
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Cliente(models.Model):
    nombre = models.CharField(verbose_name="Nombre",max_length=50)
    apellido = models.CharField(verbose_name="Apellido",max_length=50)
    activo = models.BooleanField(verbose_name="Activo",default=True)
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Servicio(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=50)
    descripcion = models.CharField(verbose_name="Descripcion", max_length=50)
    precio = models.IntegerField(verbose_name="Precio")
    activo = models.BooleanField(verbose_name="Activo", default=True)
    
    def __str__(self):
        return f"{self.nombre}"

class ReservaServicio(models.Model):
    fecha_creacion = models.DateTimeField(verbose_name="Fecha de creacion",auto_now_add=True)
    fecha_reserva = models.DateTimeField(verbose_name="Fecha de reserva")
    cliente = models.ForeignKey(Cliente,verbose_name="Cliente",on_delete=models.CASCADE,related_name="cliente")
    responsable = models.ForeignKey(Coordinador,verbose_name="Coordinador",on_delete=models.CASCADE,related_name="coordinador")
    empleado = models.ForeignKey(Empleado,verbose_name="Empleado",on_delete=models.CASCADE,related_name="empleado")
    servicio = models.ForeignKey(Servicio,verbose_name="Servicio",on_delete=models.CASCADE,related_name="servicio")
    precio = models.IntegerField(verbose_name="Precio")
    
    def get_fecha_creacion_formateada(self):
        return self.fecha_creacion.strftime("%d/%m/%Y %H:%M")
    
    def get_fecha_reserva_formateada(self):
        return self.fecha_reserva.strftime("%d/%m/%Y %H:%M")
    
    def __str__(self):
        return f"{self.cliente} {self.responsable} {self.empleado} {self.servicio}"

ProyectoAlkemy/reserva/views.py
from django.shortcuts import render
from .models import Empleado, Cliente, Coordinador, Servicio, ReservaServicio
from django.shortcuts import get_object_or_404,redirect
from datetime import datetime
from django.db import IntegrityError

# Create your views here.
def home(request):
    return render(request, "reserva/home.html")

def registrar_empleado(request):

    if request.method == "POST":        
        try:
            Empleado.objects.create(
            nombre = request.POST["nombre"],
            apellido = request.POST["apellido"],
            numero_legajo = request.POST["numero_legajo"],
            );
            return redirect('listado_empleados')
        except IntegrityError:

            return redirect('listado_empleados')
            
    return render(request, 'reserva/registrar_empleado.html')
    
def activar_empleado(request,id_empleado):
  
    empleado=Empleado.objects.get(id=id_empleado);
    empleado.activo=True;
    empleado.save();

    return redirect('listado_empleados')

def listado_empleados(request):
    empleados = Empleado.objects.all()
    context = {
        "empleados": empleados
    }
    return render(request, "reserva/listar_empleados.html", context)

def modificar_empleado(request, id_empleado):    
    empleado=Empleado.objects.get(id=id_empleado)    
    context = {
        "empleado": empleado
    }
    if request.method == "POST":  
        try:
            empleado.nombre = request.POST["nombre"]
            empleado.apellido = request.POST["apellido"]
            empleado.numero_legajo = request.POST["numero_legajo"]
            empleado.save()
            return redirect('listado_empleados')
       
        except IntegrityError:

            return redirect('listado_empleados')
          
    return render(request, "reserva/modificar_empleado.html", context)

def desactivar_empleado(request,id_empleado):
      
    empleado=Empleado.objects.get(id=id_empleado)
    empleado.activo=False
    empleado.save()

    return redirect('listado_empleados')

def listado_clientes(request):
    clientes = Cliente.objects.all()
    context = {
        "clientes": clientes
    }
    return render(request, "reserva/listar_clientes.html", context)

def registrar_cliente(request):

    if request.POST:

        Cliente.objects.create(
            nombre = request.POST["nombre"],
            apellido = request.POST["apellido"],
        )
        return redirect('listado_clientes')
        
    return render(request,'reserva/registrar_cliente.html')

def registrar_coordinador(request):

    if request.method == "POST":
        try:    
            Coordinador.objects.create(
                nombre = request.POST["nombre"],
                apellido = request.POST["apellido"],
                numero_documento = request.POST["numero_documento"]
            )
            return redirect('listado_coordinadores')
        except IntegrityError:
           return redirect('listado_coordinadores')
            
        
    return render(request,'reserva/registrar_coordinador.html')

def modificar_coordinador(request,id_coordinador):

    coordinador = get_object_or_404(Coordinador, id=id_coordinador)
    if request.method == "POST": 
        try:
            
            coordinador.nombre = request.POST["nombre"]
            coordinador.apellido = request.POST["apellido"]
            coordinador.numero_documento = request.POST["numero_documento"]
            coordinador.save()
            return redirect('listado_coordinadores')
        except IntegrityError:
            return redirect('listado_coordinadores')
    
    return render(request,'reserva/modificar_coordinador.html',{"coordinador": coordinador})

def activar_coordinador(request,id_coordinador):
      
    coordinador = Coordinador.objects.get(id=id_coordinador)
    coordinador.activo = True
    coordinador.save()
    return redirect('listado_coordinadores')

def desactivar_coordinador(request,id_coordinador):
      
    coordinador = Coordinador.objects.get(id=id_coordinador)
    coordinador.activo = False
    coordinador.save()
    return redirect('listado_coordinadores')

def desactivar_cliente(request,id_cliente):

    cliente = get_object_or_404(Cliente,id=id_cliente)
    if cliente.activo:
       cliente.activo=False
       cliente.save()
    
    return redirect('listado_clientes')

def activar_cliente(request,id_cliente):

    cliente = get_object_or_404(Cliente,id=id_cliente)
    if not cliente.activo:
       cliente.activo=True
       cliente.save()

    return redirect('listado_clientes')

def modificar_cliente(request,id_cliente):

    cliente = get_object_or_404(Cliente, id=id_cliente);
    if request.method == "POST":
        cliente.nombre = request.POST["nombre"]
        cliente.apellido = request.POST["apellido"]
        cliente.save();
        return redirect('listado_clientes')        
    
    return render(request,'reserva/modificar_cliente.html',{"cliente":cliente})

def listado_coordinadores(request):
    coordinadores = Coordinador.objects.all()
    context = {
        "coordinadores": coordinadores
    }
    return render(request, "reserva/listar_coordinador.html", context)


def registrar_servicio(request):

    if request.POST:

        Servicio.objects.create(
            nombre = request.POST["nombre"],
            descripcion = request.POST["descripcion"],
            precio = request.POST["precio"],                 
        )
        return redirect('listado_servicios')
        
    return render(request,'reserva/registrar_servicio.html')

def registrar_reserva_de_servicio(request):

    clientes=Cliente.objects.filter(activo=True)
    responsables=Coordinador.objects.filter(activo=True)
    empleados=Empleado.objects.filter(activo=True)
    servicios=Servicio.objects.filter(activo=True)
    contexto={
        "clientes":clientes,
        "responsables":responsables,
        "empleados": empleados,
        "servicios": servicios,
        "fecha_actual": get_fecha_hora_actual()
    }
    if request.method == "POST":
        ReservaServicio.objects.create(
            fecha_reserva = request.POST["fecha_reserva"],
            cliente_id = request.POST["cliente"],
            responsable_id = request.POST["responsable"],
            empleado_id = request.POST["empleado"],
            servicio_id = request.POST["opcion"],
            precio = request.POST["precio"]
        )
        return redirect('listado_reservas_de_servicios')
    
    return render(request, "reserva/registrar_reserva_de_servicio.html",contexto)

def modificar_reserva_de_servicio(request,id_reserva_servicio):
    
    reserva_servicio = get_object_or_404(ReservaServicio,id=id_reserva_servicio)
    clientes = Cliente.objects.filter(activo=True)
    responsables = Coordinador.objects.filter(activo=True)
    empleados = Empleado.objects.filter(activo=True)
    servicios = Servicio.objects.filter(activo=True)
    contexto = {
        "reserva_servicio": reserva_servicio,
        "clientes": clientes,
        "responsables": responsables,
        "empleados": empleados,
        "servicios": servicios,
        "fecha_actual": get_fecha_hora_actual()
    }
    if request.method == "POST":
        reserva_servicio.fecha_reserva = request.POST["fecha_reserva"]
        reserva_servicio.cliente_id = request.POST["cliente"]
        reserva_servicio.responsable_id = request.POST["responsable"]
        reserva_servicio.empleado_id = request.POST["empleado"]
        reserva_servicio.servicio_id = request.POST["opcion"]
        reserva_servicio.precio = request.POST["precio"]
        
        reserva_servicio.save();
        return redirect('listado_reservas_de_servicios')

    return render(request,"reserva/modificar_reserva_de_servicio.html",contexto)


def eliminar_reserva_de_servicio(request,id_reserva_servicio):
    
    reserva_servicio = get_object_or_404(ReservaServicio,id=id_reserva_servicio)
    reserva_servicio.delete()
    
    return redirect('listado_reservas_de_servicios')

def listado_reservas_de_servicios(request):

    reservas = ReservaServicio.objects.all();

    return render(request,"reserva/listar_reservas_de_servicios.html",{"reservas":reservas})

def modificar_servicio(request, id_servicio):    
    
    servicio=Servicio.objects.get(id=id_servicio)    
    
    context = {
        "servicio": servicio
    }
    if request.POST:        
        nombre = request.POST["nombre"],
        descripcion = request.POST["descripcion"],
        precio = request.POST["precio"],
        
        servicio.nombre = nombre[0]
        servicio.descripcion = descripcion[0]
        servicio.precio = int(precio[0])
        servicio.save()
        return redirect('listado_servicios')
          
    return render(request, "reserva/modificar_servicio.html", context)

def desactivar_servicio(request,id_servicio):

    servicio = get_object_or_404(Servicio,id=id_servicio)
    if servicio.activo:
       servicio.activo=False
       servicio.save()
    
    return redirect('listado_servicios')

def activar_servicio(request,id_servicio):

    servicio = get_object_or_404(Servicio,id=id_servicio)
    if not servicio.activo:
       servicio.activo=True
       servicio.save()

    return redirect('listado_servicios')

def listado_servicios(request):
    servicios = Servicio.objects.all()
    context = {
        "servicios": servicios
    }
    return render(request, "reserva/listar_servicios.html", context)

def get_fecha_hora_actual():
    
    fecha_actual = datetime.now()
    fecha_actual_medianoche=datetime(fecha_actual.year,fecha_actual.month,fecha_actual.day);
    return fecha_actual_medianoche.strftime('%Y-%m-%d %H:%M:%S')

ProyectoAlkemy/reserva/templates/reserva/modificar_cliente.html
{% load static %}

<!-- Custom ICO -->
<link rel="shortcut icon" href="{% static 'img/resetImage.ico' %}" type="image/x-icon"> 
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
<!-- Bootstrap -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" /> 
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/formularios.css' %}">

<title>La Reserva</title>

<div class="base-container">
    <img src="{% static 'img/BANNER-01.png' %}" alt="" width="100%" id="fondo">
    <div class="banner">
        
    </div>
    <div class="top">
        <div class="logo">            
            <img src="{% static 'img/LaReserva.png' %}" alt="" id="logo">
        </div>
        <div class="navegador">            
            <a href="{% url 'listado_empleados' %}">EMPLEADOS</a>
            <a href="{% url 'listado_coordinadores' %}">COORDINADORES</a>
            <a href="{% url 'listado_clientes' %}">CLIENTES</a>
            <a href="{% url 'listado_servicios' %}">SERVICIOS</a>
            <a href="{% url 'listado_reservas_de_servicios' %}">RESERVAS DE SERVICIOS</a>  
        </div>
    </div>
    <div class="base-formulario">
        <div class="titulo">
            <h2 class="mb-4 text-center">Modificar Cliente</h2>
        </div>

        <div>
            <form method="post">
                <div class="formulario">
                    {% csrf_token %}
                    <div>
                        <label for="id_nombre">Nombre :</label>
                        <input type="text" value="{{cliente.nombre}}" class="form-control" pattern="[A-Za-z ]+" required
                        title="Ingresa solo letras" name="nombre" id="id_nombre">
                    </div>
                    <div>
                        <label for="id_apellido">Apellido :</label>
                    <input type="text" value="{{cliente.apellido}}" class="form-control" pattern="[A-Za-z ]+" required
                        title="Ingresa solo letras" name="apellido" id="id_apellido">
                    </div>                 
                    <div>
                        <button class="boton" type="submit"><a href=""><span>Aceptar</span></a></button>
                    </div>
                    <div>
                        <a class="cancelar" href="{% url 'listado_clientes' %}"><span>Cancelar</span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
   
</div>

ProyectoAlkemy/reserva/templates/reserva/modificar_coordinador.html
{% load static %}

<!-- Custom ICO -->
<link rel="shortcut icon" href="{% static 'img/resetImage.ico' %}" type="image/x-icon"> 
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
<!-- Bootstrap -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" /> 
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/formularios.css' %}">

<title>La Reserva</title>

<div class="base-container">
    <img src="{% static 'img/BANNER-01.png' %}" alt="" width="100%" id="fondo">
    <div class="banner">
        
    </div>
    <div class="top">
        <div class="logo">            
            <img src="{% static 'img/LaReserva.png' %}" alt="" id="logo">
        </div>
        <div class="navegador">            
            <a href="{% url 'listado_empleados' %}">EMPLEADOS</a>
            <a href="{% url 'listado_coordinadores' %}">COORDINADORES</a>
            <a href="{% url 'listado_clientes' %}">CLIENTES</a>
            <a href="{% url 'listado_servicios' %}">SERVICIOS</a>
            <a href="{% url 'listado_reservas_de_servicios' %}">RESERVAS DE SERVICIOS</a>  
        </div>
    </div>
    <div class="base-formulario">
        <div class="titulo">
            <h2 class="mb-4 text-center">Modificar Coordinador</h2>
            {% if messages %}
                {% for message in messages %}
                    <div class="message-{{message.tags}} p-2 mb-1 text-center rounded text-dark">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div>
            <form method="post">
                <div class="formulario">
                    {% csrf_token %}
                    <div>
                        <label class="mb-2" for="id_nombre">Nombre :</label>
                        <input type="text" value="{{coordinador.nombre}}" class="form-control" pattern="[A-Za-z ]+" required title="Ingresa solo letras" name="nombre" id="id_nombre">
                    </div>
                    <div>
                        <label class="mb-2" for="id_apellido">Apellido :</label>
                        <input type="text" value="{{coordinador.apellido}}" class="form-control" pattern="[A-Za-z ]+" required title="Ingresa solo letras" name="apellido" id="id_apellido">
                    </div>
                    <div>
                        <label class="mb-2" for="id_numero_documento">DNI</label>
                        <input type="number" value="{{coordinador.numero_documento}}" class="form-control" name="numero_documento" id="id_numero_documento" required>
                    </div> 
                    <div>                        
                    </div>                  
                    <div>
                        <button class="boton" type="submit"><a href=""><span>Aceptar</span></a></button>
                    </div>
                    <div>
                        <a class="cancelar" href="{% url 'listado_coordinadores' %}"><span>Cancelar</span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
   
</div>

ProyectoAlkemy/reserva/templates/reserva/modificar_servicio.html
{% load static %}

<!-- Custom ICO -->
<link rel="shortcut icon" href="{% static 'img/resetImage.ico' %}" type="image/x-icon"> 
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
<!-- Bootstrap -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" /> 
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/formularios.css' %}">

<title>La Reserva</title>

<div class="base-container">
    <img src="{% static 'img/BANNER-01.png' %}" alt="" width="100%" id="fondo">
    <div class="banner">
        
    </div>
    <div class="top">
        <div class="logo">            
            <img src="{% static 'img/LaReserva.png' %}" alt="" id="logo">
        </div>
        <div class="navegador">            
            <a href="{% url 'listado_empleados' %}">EMPLEADOS</a>
            <a href="{% url 'listado_coordinadores' %}">COORDINADORES</a>
            <a href="{% url 'listado_clientes' %}">CLIENTES</a>
            <a href="{% url 'listado_servicios' %}">SERVICIOS</a>
            <a href="{% url 'listado_reservas_de_servicios' %}">RESERVAS DE SERVICIOS</a>  
        </div>
    </div>
    <div class="base-formulario">
        <div class="titulo">
            <h2 class="mb-4 text-center">Modificar Servicio</h2>
            {% if messages %}
                {% for message in messages %}
                    <div class="message-{{message.tags}} p-2 mb-1 text-center rounded text-dark">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div>
            <form method="post">
                <div class="formulario">
                    {% csrf_token %}
                    <div>
                        <label for="id_nombre">Nombre :</label>
                        <input type="text" value="{{servicio.nombre}}" class="form-control" name="nombre" id="id_nombre" required>
                    </div>                    
                    <div>
                        <label for="id_precio">Precio</label>
                        <input type="number" value="{{servicio.precio}}" class="form-control" name="precio" id="id_nprecio" required>
                    </div> 
                    <div>
                        <label for="id_descripcion">Descripcion :</label>
                        <input type="text" value="{{servicio.descripcion}}" class="form-control" name="descripcion" id="id_descripcion" required>
                    </div>
                    <div>                        
                    </div>                  
                    <div>
                        <button class="boton" type="submit"><a href=""><span>Aceptar</span></a></button>
                    </div>
                    <div>
                        <a class="cancelar" href="{% url 'listado_servicios' %}"><span>Cancelar</span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>  
   
</div>

ProyectoAlkemy/reserva/templates/reserva/registrar_coordinador.html
{% load static %}

<!-- Custom ICO -->
<link rel="shortcut icon" href="{% static 'img/resetImage.ico' %}" type="image/x-icon"> 
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
<!-- Bootstrap -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" /> 
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/formularios.css' %}">

<title>La Reserva</title>

<div class="base-container">
    <img src="{% static 'img/BANNER-01.png' %}" alt="" width="100%" id="fondo">
    <div class="banner">
        
    </div>
    <div class="top">
        <div class="logo">            
            <img src="{% static 'img/LaReserva.png' %}" alt="" id="logo">
        </div>
        <div class="navegador">            
            <a href="{% url 'listado_empleados' %}">EMPLEADOS</a>
            <a href="{% url 'listado_coordinadores' %}">COORDINADORES</a>
            <a href="{% url 'listado_clientes' %}">CLIENTES</a>
            <a href="{% url 'listado_servicios' %}">SERVICIOS</a>
            <a href="{% url 'listado_reservas_de_servicios' %}">RESERVAS DE SERVICIOS</a>  
        </div>
    </div>
    <div class="base-formulario">
        <div class="titulo">
            <h2 class="mb-4 text-center">Registrar Coordinador</h2>
            {% if messages %}
                {% for message in messages %}
                    <div class="message-{{message.tags}} p-2 mb-1 text-center rounded text-dark">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div>
            <form method="post">
                <div class="formulario">
                    {% csrf_token %}
                    <div>
                        <label class="mb-2" for="id_nombre">Nombre :</label>
                        <input type="text" class="form-control" pattern="[A-Za-z ]+" required title="Ingresa solo letras" name="nombre" id="id_nombre">
                    </div>
                    <div>
                        <label class="mb-2" for="id_apellido">Apellido :</label>
                        <input type="text" class="form-control" pattern="[A-Za-z ]+" required title="Ingresa solo letras" name="apellido" id="id_apellido">
                    </div>
                    <div>
                        <label class="mb-2" for="id_numero_documento">DNI</label>
                        <input type="number" class="form-control" name="numero_documento" id="id_numero_documento" required>
                    </div> 
                    <div>                        
                    </div>                  
                    <div>
                        <button class="boton" type="submit"><a href=""><span>Aceptar</span></a></button>
                    </div>
                    <div>
                        <a class="cancelar" href="{% url 'listado_coordinadores' %}"><span>Cancelar</span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
   
</div>